[default]
faces = ["(o_o)"]

[cat]
faces = ["(^._.^)"]

[dog]
faces = ["(ᵔᴥᵔ)"]

[fumo_1]
faces = ["ᗜˬᗜ", "ᗜ˰ᗜ"]

[fumo_2]
faces = ["ᗜ ̫ ᗜ"]

[fumo_3]
faces = ["ᗜ‿ᗜ"]

[x]
faces = ["X‿X", "-‿X", "X‿-"]

[zero]
faces = ["0x0", "-x-", "0x0"]

[blinkcat]
faces = [
'''
 /\_/\
( o.o )
 > ^ <
''',
'''
 /\_/\
( ^.^ )
 > ^ <
'''
]

[dance_cat]
faces = [
'''
 　彡 ⌒ ミ
　（´･ω･｀） ))
(( (　つ　ヽ、
　　〉 とノ　)))
　（__ノ^(＿)
''',
'''
 　 彡 ⌒ ミ
　（´･ω･｀）
　γ　 と )　))
((( ヽつ 〈
　（＿)^(__)
'''
]

[dance_cat1]
faces = [
'''
　　　 彡⌒ ミ　　　　　　♪
　　　(´･ω･｀)　　♪
　　　（ つ　つ
　((　（⌒ __)　))
　　　　し' っ
''',
'''
　　♪　 彡⌒ ミ
　　　 ∩´･ω･｀) 　　♪
　　　　ヽ　⊂ノ
　　　(( （　 ⌒)　　))
　　　　　c し'
'''
]

[dance_cat2]
faces = [
'''
 　　　　∧＿＿∧　　　♪
　　　 （´・ω・｀∩
　　 　　o　　　,ﾉ
　　　　Ｏ＿　.ﾉ
♪　　　 　 (ノ
''',
'''
　　　　∧＿＿∧　♪
　　　 ∩・ω・｀）
　　　 |　　 ⊂ﾉ
　　　｜　　 _⊃　　♪
　　　 し ⌒
'''
]
